#!/usr/bin/env bash

reset="\001\033[0m\002"
cursor="\e[3 q"

bseq="\x01\033["
eseq="\x02"

green="${bseq}0;38;2;169;182;101m${eseq}"
red="${bseq}0;38;2;234;105;98m${eseq}"
yellow="${bseq}0;38;2;216;166;87m${eseq}"

yellowbg="${bseq}0;48;2;216;166;87m${bseq}38;2;40;40;40m${eseq}"
redbg="${bseq}0;48;2;234;105;98m${bseq}38;2;40;40;40m${eseq}"


prompter () {
prompt=" ${PWD/#$HOME/'~'} ${reset}${yellow}\n"

  if [[ "$?" == "0" ]]; then
    echo -e "\n${yellowbg}${prompt}${green}>> ${reset}"
  else
    echo -e "\n${red}${prompt}>> ${reset}"
  fi
}

# Enable vi mode indicator
bind "set show-mode-in-prompt on"
bind "set vi-ins-mode-string \"\""
bind "set vi-cmd-mode-string \"${redbg} C ${reset}${red}${reset} \""

PS1='$(prompter)'
